name: chatme
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0

#  Riverpod
  flutter_riverpod: ^3.0.0-dev.17
  #  riverpod_annotation: ^3.0.0-dev.17

#  Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

#  Lottie
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  shadex: ^1.0.2
  palette_generator: ^0.3.3+7

#  Crypto
  crypto: ^3.0.6
  firebase_messaging: ^14.0.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#  build_runner: ^2.6.0
#  riverpod_generator: ^3.0.0-dev.17
#  riverpod_lint: ^3.0.0-dev.17
#  custom_lint: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: Klavika
      fonts:
        - asset: assets/fonts/Klavika/klavika-light.otf
          weight: 100
        - asset: assets/fonts/Klavika/klavika-medium.otf
          weight: 300
        - asset: assets/fonts/Klavika/klavika-bold.otf
          weight: 700

